# Generated by Django 3.2.4 on 2021-06-26 20:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to=app.models.user_directory_path),
        ),
    ]
