# Generated by Django 3.2.3 on 2021-06-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210624_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='images')),
                ('display', models.BooleanField(default=False)),
                ('link', models.CharField(max_length=255)),
                ('slider_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='latestblog',
            name='blog_discription',
        ),
        migrations.AddField(
            model_name='latestblog',
            name='blog_description',
            field=models.TextField(default=999),
            preserve_default=False,
        ),
    ]
