# Generated by Django 3.2.4 on 2021-08-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('', 'Prefer not to mention')], max_length=50, null=True),
        ),
    ]
